ROW_LABELS:
  ROW_0     : "Time"
  ROW_1     : "Longitude"
  ROW_2     : "N/S"
  ROW_3     : "Latitude"
  ROW_4     : "E/W"
  ROW_5     : "Altitude (m)"
  ROW_6     : "Altitude (ft)"
  ROW_7     : "Pressure (mB)"
  ROW_8     : "Internal Temp (°)"
  ROW_9     : "External Temp (°)"
  ROW_10    : "Accel X (milli G's)"
  ROW_11    : "Accel Y (milli G's)"
  ROW_12    : "Accel Z (milli G's)"

ROW_VARS:
  ROW_0     : "timeUTC_out"
  ROW_1     : "longGPS_out"
  ROW_2     : "longNS_out"
  ROW_3     : "latGPS_out"
  ROW_4     : "latEW_out"
  ROW_5     : "alt_m_out"
  ROW_6     : "alt_ft_out"
  ROW_7     : "press_out"
  ROW_8     : "int_temp_out"
  ROW_9     : "ext_temp_out"
  ROW_10    : "accel_x_out"
  ROW_11    : "accel_y_out"
  ROW_12    : "accel_z_out"

