APP:
  DEBUG: True
  # Only accepts True or False

ROW_LABELS:
  ROW_0     : "ROW0"
  ROW_1     : "ROW1"
  ROW_2     : "ROW2"
  ROW_3     : "ROW3"

ROW_VARS:
  ROW_0     : "ROW0_OUT"
  ROW_1     : "ROW1_OUT"
  ROW_2     : "ROW2_OUT"
  ROW_3     : "ROW3_OUT"

SDCARD_SETUP:
  IMAGE_DATA          : False
  # only accepts true or false (hasn't been tested)
  NUM_CONFIG_BLOCKS   : 0
  # number of configuration blocks at beginning of sd card
  # 0 - inf (typically has number of data points) needs to be set to int
  NUM_DATA_BLOCKS     : 1
  # number of blocks per data point 1 - inf
  NUM_BYTES_DB_0      : 8
  # number of bytes needed to be read in from that sd card block

DB_0:
  BYTE_0    : "BYTE_0_IN"
  BYTE_1    : "BYTE_1_IN"
  BYTE_2    : "BYTE_2_IN"
  BYTE_3    : "BYTE_3_IN"
  BYTE_4    : "BYTE_4_IN"
  BYTE_5    : "BYTE_5_IN"
  BYTE_6    : "BYTE_6_IN"
  BYTE_7    : "BYTE_7_IN"

MATH:
